services:
  doujin-api:
    build: .
    image: doujin-api:9422
    container_name: doujin-api
    ports:
      - "9422:9422"
    environment:
      PORT: 9422
      APP_DATA: /app/data
    volumes:
      - ./data:/app/data
      - ./content:/app/content
    restart: unless-stopped
